{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: career-copilot-ingress
  annotations:
    {{- if .Values.ingress.certManagerAnnotations }}
    cert-manager.io/cluster-issuer: {{ .Values.certManager.issuer | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: career-copilot-client
                port:
                  number: 80
  {{- if .Values.ingress.certManagerAnnotations }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: career-copilot-tls
  {{- end }}
{{- end }}
