apiVersion: v1
kind: Service
metadata:
  name: career-copilot-server
spec:
  selector:
    app: career-copilot-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.server.port }}
  type: ClusterIP
