apiVersion: v1
kind: Service
metadata:
  name: career-copilot-client
spec:
  selector:
    app: career-copilot-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.client.port }}
  type: ClusterIP
