replicaCount: 1

server:
  image: "ghcr.io/REPLACE_OWNER/REPO-server:latest"
  port: 3001
  resources: {}

client:
  image: "ghcr.io/REPLACE_OWNER/REPO-client:latest"
  port: 3000
  resources: {}

persistence:
  enabled: false
  storageClass: "local-path"
  size: "1Gi"
  mountPath: "/app/data"

certManager:
  enabled: false
  email: "admin@example.com"
  issuer: "letsencrypt-prod"

ingress:
  enabled: false
  host: example.com
  certManagerAnnotations: false
  ingressClass: "traefik"
